version: '3.8'

services:
  tourism-website:
    build: .
    ports:
      - "8080:80"
    container_name: tourism-website
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/share/nginx/html/
    restart: unless-stopped
